# Generated by Django 5.2.7 on 2025-10-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('tipo_dispositivo', models.CharField(choices=[('PC', 'PC de Escritorio'), ('NB', 'Notebook'), ('CEL', 'Celular'), ('CON', 'Consola')], default='CEL', max_length=3)),
                ('modelo', models.CharField(max_length=100)),
                ('problema', models.TextField()),
                ('estado', models.CharField(choices=[('POR', 'Por Reparar'), ('ENP', 'En Proceso'), ('REP', 'Reparado'), ('ENT', 'Entregado')], default='POR', max_length=3)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
