# Generated by Django 4.2.25 on 2025-10-23 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reparaciones', '0002_cliente_mensaje_retiroentrega_reparacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='remitente',
            new_name='asunto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='correoprueba@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='reparaciones.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='reparaciones.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retiroentrega',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='retiroentrega',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citadiagnostico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='reparaciones.cliente'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('PC', 'PC de Escritorio'), ('NB', 'Notebook'), ('CEL', 'Celular'), ('CON', 'Consola'), ('OTR', 'Otro')], default='CEL', max_length=3),
        ),
        migrations.AlterField(
            model_name='retiroentrega',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='reparaciones.cliente'),
        ),
        migrations.AlterField(
            model_name='retiroentrega',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='retiroentrega',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='retiroentrega',
            name='tipo_servicio',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('entrega', 'Entrega')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
    ]
